### ISSUE TITLE
Achim's photo should be adjusted to landscape on mobile devices.

### ISSUE THREAD

**Issue by theadamparker** [undp/newundp#11]
Currently the photo remains portrait on all screens. Correct implementation should match the design file. 
<img width="536" alt="Screen Shot 2021-09-24 at 5 36 57 PM" src="https://user-images.githubusercontent.com/2205158/134742316-a3b7b60e-0924-4a6a-a646-f5abe721254c.png">

**Comment by Jura** [comment]
@theadamparker Can you provide the actual photo? I can't extract it from Figma in decent quality

**Comment by theadamparker** [comment]
@Jura [here's the photo from Figma](https://s3-alpha-sig.figma.com/img/a5c5/079c/a9fe0b86946b9d4da0d52a1b2be1a8fd?Expires=1633910400&Signature=W9~MNc6PdRvwaF73pBeME1aoi88FHihOheMaNuh-6QGoBb-PypiyajLjtO~CgpdbOHVjtTFKJZOguocW93nXH1lQaJvlC0VbZ9kaf32LhlkuF25Ty4KJiyWxJwd0muMXmDZof2bKgGl-w8XLphTm2qVw4a84Vfh5~TXBlXf19T69-RAt4uD~qUi4OqTacPxDeXO~~qyCxAuE6WVToeZDKMLA2zB3uk-C~pscLJF7mvZO7HnNEzQ7scB0ryhCVX30k5PsSycgP6ADwR5GqoQCyPfGCPOYVojM2cLYWr1zGIj6010yrMTyUyYZS4zSPXrQXWrTZK-9r1x9DkGJkeWQnQ__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA). This is the full-resolution photo but we can also export smaller versions with different crops if it's useful
