### ISSUE TITLE
Site is missing a meta image

### ISSUE THREAD

**Issue by theadamparker** [undp/newundp#17]

**Comment by Jura** [comment]
@theadamparker let me know if you have specific image in mind, for the time being I'll be using publication's cover from https://www.undp.org/publications/undp-strategic-plan-2022-2025

**Comment by Jura** [comment]
This one: 
![image](https://user-images.githubusercontent.com/417604/135363202-ef49c288-f6aa-4f53-99f7-7453e9e8c4cb.png)
