### ISSUE TITLE
Language selector should match design file

### ISSUE THREAD

**Issue by theadamparker** [undp/newundp#6]
Should include the option to switch to published languages and download PDFs for languages without a site.
<img width="261" alt="Screen Shot 2021-09-24 at 5 27 31 PM" src="https://user-images.githubusercontent.com/2205158/134741682-becaebf6-ccf8-4a62-a6f7-40bc82581e90.png">

**Comment by Jura** [comment]
@theadamparker check it out: https://jura.github.io/newundp/
