### ISSUE TITLE
Sidebar nav is currently empty

### ISSUE THREAD

**Issue by theadamparker** [undp/newundp#9]
This should be populated with site sections.

Currently looks like this
<img width="947" alt="Screen Shot 2021-09-24 at 5 32 17 PM" src="https://user-images.githubusercontent.com/2205158/134741963-9a7d7597-d6bc-4861-9629-0a589a7abec5.png">
:

**Comment by Jura** [comment]
@theadamparker I thought we agreed that it is not required for such small site. Do you still think we need it there?

**Comment by Jura** [comment]
Damn, just removed them yesterday...
